### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PritK99** [SurajSonawane2415/MazeBlaze#2]
- Add documentation for the work done. Refer ```documentation/``` folder from MazeBlaze-v2.1 repository.

**Comment by SurajSonawane2415** [comment]
@PritK99 @RajGupta17  we have completed the documentation and file structure. We have also added documentation for the tasks we've completed. Please review and let us know if any improvements are needed.

**Comment by PritK99** [comment]
- Fix typos and spelling errors in ```/README.md```. Use tools such as Grammarly to ensure all spellings are correct.
- Refer file structure tree in ```/README.md``` from MazeBlaze-v2
- Keep the names of all README consistent as ```README.md```
- Keep the folder structure consistent for both sub folders in ```tasks/```

**Comment by SurajSonawane2415** [comment]
@PritK99 @RajGupta17 all changes are done.
